//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowMenu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ShowMenu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowMenu", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ShowMenuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowWeight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        float ShowWeight(string PizzaSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowWeight", ReplyAction="*")]
        System.Threading.Tasks.Task<float> ShowWeightAsync(string PizzaSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        float ShowPrice(string PizzaSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<float> ShowPriceAsync(string PizzaSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShowDetails(string PizzaSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ShowDetailsAsync(string PizzaSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ShowDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateDatabase(System.Data.DataTable newTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateDatabaseAsync(System.Data.DataTable newTable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebService1Soap>, Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ShowMenu() {
            return base.Channel.ShowMenu();
        }
        
        public System.Threading.Tasks.Task<string[]> ShowMenuAsync() {
            return base.Channel.ShowMenuAsync();
        }
        
        public float ShowWeight(string PizzaSelected) {
            return base.Channel.ShowWeight(PizzaSelected);
        }
        
        public System.Threading.Tasks.Task<float> ShowWeightAsync(string PizzaSelected) {
            return base.Channel.ShowWeightAsync(PizzaSelected);
        }
        
        public float ShowPrice(string PizzaSelected) {
            return base.Channel.ShowPrice(PizzaSelected);
        }
        
        public System.Threading.Tasks.Task<float> ShowPriceAsync(string PizzaSelected) {
            return base.Channel.ShowPriceAsync(PizzaSelected);
        }
        
        public string ShowDetails(string PizzaSelected) {
            return base.Channel.ShowDetails(PizzaSelected);
        }
        
        public System.Threading.Tasks.Task<string> ShowDetailsAsync(string PizzaSelected) {
            return base.Channel.ShowDetailsAsync(PizzaSelected);
        }
        
        public System.Data.DataTable ShowDatabase() {
            return base.Channel.ShowDatabase();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowDatabaseAsync() {
            return base.Channel.ShowDatabaseAsync();
        }
        
        public string UpdateDatabase(System.Data.DataTable newTable) {
            return base.Channel.UpdateDatabase(newTable);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDatabaseAsync(System.Data.DataTable newTable) {
            return base.Channel.UpdateDatabaseAsync(newTable);
        }
    }
}
